// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import static edu.wpi.first.units.Units.RotationsPerSecond;
import static edu.wpi.first.units.Units.RotationsPerSecondPerSecond;
import static edu.wpi.first.units.Units.Second;

import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.FeedbackConfigs;
import com.ctre.phoenix6.configs.MotionMagicConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.signals.NeutralModeValue;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.CombinedStallHandler;
import frc.robot.Constants;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class ElevatorS1 extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public TalonFX stage1motor;
;
    private DigitalInput elevatorBottomSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
;
    TalonFXConfiguration elevatorLowerConfig = new TalonFXConfiguration();
;
    private final MotionMagicVoltage m_motionMagicReqL = new MotionMagicVoltage(0);
;
    public double elevatorStage1Target;
;
    public CombinedStallHandler stage1CombinedStallHandler;
    /**
    *
    */
    public ElevatorS1() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        stage1motor = new TalonFX(14);
        elevatorBottomSwitch = new DigitalInput(0);
        FeedbackConfigs elevatorLowerFeedback = elevatorLowerConfig.Feedback;
        elevatorLowerFeedback.SensorToMechanismRatio = 20;
        CurrentLimitsConfigs elevatorLowerCurrent = elevatorLowerConfig.CurrentLimits;
        elevatorLowerCurrent.StatorCurrentLimit = Constants.ElevatorConstants.stage1CurrentLimit;
      
        MotorOutputConfigs elevatorLowerOutput = elevatorLowerConfig.MotorOutput;
        elevatorLowerOutput.Inverted = InvertedValue.Clockwise_Positive;
        elevatorLowerOutput.NeutralMode = NeutralModeValue.Brake;

        MotionMagicConfigs motionMagicL = elevatorLowerConfig.MotionMagic;
        motionMagicL.withMotionMagicCruiseVelocity(RotationsPerSecond.of(10)) // (meachanism) rotations per second cruise
                .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(10))
                .withMotionMagicJerk(RotationsPerSecondPerSecond.per(Second).of(100));

        Slot0Configs lowerSlot0 = elevatorLowerConfig.Slot0;
        lowerSlot0.kP = 60; // A position error of 0.2 rotation/s results in 12 V output
        lowerSlot0.kI = 0; // No output for integrated error
        lowerSlot0.kD = 0.5; // A velocity error of 1 rps results in 0.5 V output
        lowerSlot0.kV = 5.226; // A velocity target of 1 rps results in 0.12 V output
        lowerSlot0.kS = 0.15296; // Add 0.25 V output to overcome static friction
        lowerSlot0.kA = 0.055325; // An acceleration of 1 rps/s requires 0.01 V output

        StatusCode statusL = StatusCode.StatusCodeNotInitialized;
        for (int i = 0; i < 5; ++i) {
            statusL = stage1motor.getConfigurator().apply(elevatorLowerConfig);
            if (statusL.isOK())
                break;
        }
        if (!statusL.isOK()) {
            System.out.println("Could not configure device. Error: " + statusL.toString());
        }

        stage1CombinedStallHandler = new CombinedStallHandler(stage1motor);

    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putNumber("Bottom Pos", stage1motor.getPosition().getValueAsDouble());
        
        SmartDashboard.putBoolean("bottomSwitch", getBottomSwitch());
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public boolean getBottomSwitch() {
        return elevatorBottomSwitch.get();
    }

    public boolean isMotorOneAtPos() {
    
        return Math.abs(stage1motor.getPosition().getValueAsDouble() - elevatorStage1Target) < .1;
    }

    public void setElevatorPosition() {
        stage1motor.setControl(
                m_motionMagicReqL.withPosition(elevatorStage1Target).withSlot(0));
            
    } 

    public void stopMotor() {
        stage1motor.set(0);
    }

    public void setElevatorZeroingS1(){
        if (getBottomSwitch()) {
            stage1motor.set(0);
        } else {
            stage1motor.set(-.75);
        }
    }

    public void setElevatorZeroingS1Upward() {
        if (getBottomSwitch()) {
            stage1motor.set(0);
        } else {
            stage1motor.set(0.2);
        }
    }

    public void setElevatorHomingS1(){
        if (!getBottomSwitch()) {
            stage1motor.set(0);
        } else {
            stage1motor.set(0.1);
        }
    }

    public void setStage1MotorPosition(double position){
        stage1motor.setPosition(position);
    }
    
}