// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import static edu.wpi.first.units.Units.RotationsPerSecond;
import static edu.wpi.first.units.Units.RotationsPerSecondPerSecond;
import static edu.wpi.first.units.Units.Second;

import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.FeedbackConfigs;
import com.ctre.phoenix6.configs.MotionMagicConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.signals.NeutralModeValue;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.CombinedStallHandler;
import frc.robot.Constants;
import frc.robot.Robot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class ElevatorS2 extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public TalonFX stage2motor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    TalonFXConfiguration elevatorUpperConfig = new TalonFXConfiguration();
    private final MotionMagicVoltage m_motionMagicReqU = new MotionMagicVoltage(0);

    public double elevatorStage2Target;
    public CombinedStallHandler stage2CombinedStallHandler;

    /**
    *
    */
    public ElevatorS2() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        stage2motor = new TalonFX(15);
        FeedbackConfigs elevatorUpperFeedback = elevatorUpperConfig.Feedback;
        elevatorUpperFeedback.SensorToMechanismRatio = 45;
        CurrentLimitsConfigs elevatorUpperCurrent = elevatorUpperConfig.CurrentLimits;
        elevatorUpperCurrent.StatorCurrentLimit = Constants.ElevatorConstants.stage2CurrentLimit;

        MotorOutputConfigs elevatorUpperOutput = elevatorUpperConfig.MotorOutput;
        elevatorUpperOutput.Inverted = InvertedValue.Clockwise_Positive;
        elevatorUpperOutput.NeutralMode = NeutralModeValue.Brake;
        
        /* Configure Motion Magic */
        MotionMagicConfigs motionMagicU = elevatorUpperConfig.MotionMagic;
        motionMagicU.withMotionMagicCruiseVelocity(RotationsPerSecond.of(9999)) // (meachanism) rotations per second cruise
                .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(10000))
                .withMotionMagicJerk(RotationsPerSecondPerSecond.per(Second).of(0));

        Slot0Configs upperSlot0 = elevatorUpperConfig.Slot0;
        upperSlot0.kP = 25; // A position error of 0.2 rotations results in 12 V output
        upperSlot0.kI = 0.25; // No output for integrated error
        upperSlot0.kD = 0; // A velocity error of 1 rps results in 0.5 V output
        upperSlot0.kV = 5.1659; // A velocity target of 1 rps results in 0.12 V output
        upperSlot0.kS = 0.051841; // Add 0.25 V output to overcome static friction
        upperSlot0.kA = 0.095406; // An acceleration of 1 rps/s requires 0.01 V output

        StatusCode statusU = StatusCode.StatusCodeNotInitialized;
        for (int i = 0; i < 5; ++i) {
            statusU = stage2motor.getConfigurator().apply(elevatorUpperConfig);
            if (statusU.isOK())
                break;
        }
        if (!statusU.isOK()) {
            System.out.println("Could not configure device. Error: " + statusU.toString());
        }

        stage2CombinedStallHandler = new CombinedStallHandler(stage2motor);

    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putNumber("Top Pos", stage2motor.getPosition().getValueAsDouble());
        SmartDashboard.putBoolean("Stage 2", Robot.getInstance().getTopStage2());

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public boolean getTopSwitch() {
        return Robot.getInstance().getTopStage2();
    }

    public boolean isMotorTwoAtPos() {
        return Math.abs(stage2motor.getPosition().getValueAsDouble() - elevatorStage2Target) < .1;
    }

    public void setElevatorPosition() {
        stage2motor.setControl(
                m_motionMagicReqU.withPosition(elevatorStage2Target).withSlot(0));
            
    } 

    public void stopMotor() {
        stage2motor.set(0);
    }

    public void setElevatorZeroingS2(){
        if (getTopSwitch()) {
           stage2motor.set(0);
        } else {
            stage2motor.set(1);
        }
    }

    public void setElevatorHomingS2(){
        if (!getTopSwitch()) {
           stage2motor.set(0);
        } else {
            stage2motor.set(-0.1);
        }
    }

    public void increase(){
            elevatorStage2Target += 0.1f;
    }

    public void decrease(){
        if (elevatorStage2Target - 0.1f >= Constants.ElevatorConstants.stage2LowerLimit)
            elevatorStage2Target -= 0.1f;
    }

    public void setStage2MotorPosition(double position){
        stage2motor.setPosition(position);
    }
    
}
