// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

package frc.robot.commands.AutonomousCommands;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import edu.wpi.first.wpilibj2.command.Commands;
import frc.robot.PoseSetter;
import frc.robot.Robot;
import frc.robot.commands.MoveElevatorS1;
import frc.robot.commands.MoveElevatorS2;
import frc.robot.commands.MoveShoulder;
import frc.robot.subsystems.Algae;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.ElevatorS1;
import frc.robot.subsystems.ElevatorS2;
import frc.robot.subsystems.Shoulder;
/**
 *
 */
public class AutonGrabAlgaeL3 extends SequentialCommandGroup {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    public AutonGrabAlgaeL3(Shoulder m_shoulder, ElevatorS1 m_elevatorS1, ElevatorS2 m_elevatorS2, Algae m_algae){
        // Add Commands here:
        // Also add parallel commands using the
        //
        addCommands(
              new InstantCommand(() -> Robot.getInstance().goalArrangementOthers(PoseSetter.AlgaeGrab + "L3")),
              new MoveShoulder(m_shoulder),
              Commands.parallel(
                  new MoveElevatorS1(m_elevatorS1),
                  new MoveElevatorS2(m_elevatorS2)
              ),
              new AutonAlgaeIntake(m_algae)
        );
        
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
